version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-net

  customer-service:
    build:
      context: ./customer-service
      dockerfile: dockerfile
    container_name: customer-service
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - app-net

  order-service:
    build:
      context: ./order-service
      dockerfile: dockerfile
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - app-net
    depends_on:
      - customer-service

networks:
  app-net:
    driver: bridge